import type { Metadata } from "next";
import { Suspense } from "react";
import Loading from "./loading";
import { useQueryStore } from "@/store/store";
import {getSlug} from "@/lib/logic";

// export const metadata: Metadata = {
//   title: "Job Info",
//   description: "Generated by create next app",
// };

type ParamsType = {
  slug: string;
};

export async function generateMetadata({ params }: { params: ParamsType }) {
  const { slug } = params;
 // let x = decodeURIComponent(slug)
 // await getSlug(x)
  return {
    title: `Job Details`,
    description: "",
  };
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Suspense fallback={<Loading/>}>
    <div className="flex h-[calc(100vh-6.5rem)] bg-gray-900">
      {children}
    </div>
    </Suspense>
  );
}
