import type { Metadata } from "next";
import { Suspense } from "react";
import Loading from "./loading";
import { useQueryStore } from "@/store/store";

 export const metadata: Metadata = {
   title: "Job Info",
   description: "Generated by create next app",
 };


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Suspense fallback={<Loading/>}>
    <div className="flex h-[calc(100vh-6.5rem)] bg-gray-900">
      {children}
    </div>
    </Suspense>
  );
}
