import type { Metadata } from "next";
import { PT_Sans,Roboto } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import Header from "@/components/Header";
import { Toaster } from "react-hot-toast";
import Footer from "@/components/Footer";

const inter =Roboto({
  weight: '400',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: "Hiretopia",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
      <link rel="icon" href="https://raw.githubusercontent.com/amitkroutthedev/hiretopia/main/assets/added_-removebg-preview.png" sizes="any" />
        <body className={`${inter.className}`}>
        <Header />
        <Toaster position="top-right" />
        <div className="h-[calc(100vh-6.5rem)] overflow-y-auto">
          {children}
        </div>
          <Footer/>
          </body>
      </html>
    </ClerkProvider>
  );
}
